/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import Business.BaseBusyness;
import Business.MicroblogBusiness;
import Business.UploadBean;
import Entity.CountNum;
import struts.form.CommentsAddForm;
import struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-12-2013
 * 
 * XDoclet definition:
 * @struts.action path="/addComments" name="commentsAddForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/Homepage.jsp"
 */
public class AddCommentsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CommentsAddForm commentsAddForm = (CommentsAddForm) form;// TODO Auto-generated method stub
		MicroblogBusiness mb=new MicroblogBusiness();
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
        if(mb.addComments(commentsAddForm,u.getID())){
			return mapping.findForward("success");
		}
		return null;
	}
}