/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.MicroblogBusiness;

import struts.form.AddForwardDetailForm;
import struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-18-2013
 * 
 * XDoclet definition:
 * @struts.action path="/addForward" name="addForwardDetailForm" scope="request" validate="true"
 */
public class AddForwardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddForwardDetailForm addForwardDetailForm = (AddForwardDetailForm) form;// TODO Auto-generated method stub
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
		MicroblogBusiness mb=new MicroblogBusiness();
		if(mb.addForwardDetail(addForwardDetailForm,u.getID())){
			return mapping.findForward("success");
		}else{
			return mapping.findForward("fail");
		}
	}
}