/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.AdminBusyness;

/** 
 * MyEclipse Struts
 * Creation date: 11-03-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="fail" path="/queryUsers.do"
 * @struts.action-forward name="success" path="/queryUsers.do?flag=delUser"
 */
public class DeleteUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String userid = request.getParameter("userid");
        AdminBusyness ab = new AdminBusyness();
        ab.deleteUser(userid);
        return mapping.findForward("success");
	}
}