/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.MicroblogBusiness;

/** 
 * MyEclipse Struts
 * Creation date: 11-18-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/queryForwardArticles.do"
 */
public class DeleteForwardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String forward_id = request.getParameter("forward_id");
		MicroblogBusiness mb=new MicroblogBusiness();
		mb.deleteForward(forward_id);
		return mapping.findForward("success");
	}
}