/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;
import Business.MicroblogBusiness;
import Entity.CountNum;

/** 
 * MyEclipse Struts
 * Creation date: 11-14-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/queryFans.do"
 */
public class DeleteFanAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
		String fan_id = request.getParameter("fan_id");
		MicroblogBusiness mb=new MicroblogBusiness();
		mb.deleteFan(fan_id,u.getID());
		mb.deleteOppositeFollow(u.getID(),fan_id);
		mb.updateSubFanNum(u.getID());
		mb.updateSubFollowNum(fan_id);
		CountNum cn=mb.getNum(u.getID());
		session.setAttribute("num",cn);
		return mapping.findForward("success");
	}
}