/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.FollowForm;
import struts.form.LoginForm;
import Business.MicroblogBusiness;
import Entity.CountNum;

/** 
 * MyEclipse Struts
 * Creation date: 11-14-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/queryFollows"
 */
public class DeleteFollowAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
		String follow_id = request.getParameter("follow_id");
		MicroblogBusiness mb=new MicroblogBusiness();
		mb.deleteFollow(follow_id,u.getID());
		mb.deleteOppositeFan(u.getID(),follow_id);
		mb.updateSubFollowNum(u.getID());
		mb.updateSubFanNum(follow_id);
		mb.changeFollowstatus1(follow_id,u.getID());
		CountNum cn=mb.getNum(u.getID());
		session.setAttribute("num",cn);
		return mapping.findForward("success");
	}
}