/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.AdminBusyness;
import Entity.Noticeboard;


/** 
 * MyEclipse Struts
 * Creation date: 11-03-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="update" path="/UpdateNoticeboard.jsp"
 * @struts.action-forward name="detail" path="/DetailNoticeboard.jsp"
 */
public class DetailNoticeboardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String notice_id=request.getParameter("notice_id");
		AdminBusyness ab=new AdminBusyness();
		Noticeboard n=ab.getNoticeboard(notice_id);
		request.setAttribute("notice",n);
		String flag=request.getParameter("flag");
		if("update".equals(flag)){
			return mapping.findForward("update");
		}else{
			return mapping.findForward("detail");
		}
		
	}
}