/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;
import Business.MemberBusyness;
import Entity.Userinfo;

/** 
 * MyEclipse Struts
 * Creation date: 11-01-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="detail" path="DetailUser.jsp"
 */
public class DetailUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		MemberBusyness mb=new MemberBusyness();
		String userid=request.getParameter("userid");
		Userinfo ui=mb.getMemberDetail(userid);
		request.setAttribute("detailUser",ui);
		return mapping.findForward("detail");
	
	}
}
