/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.MicroblogBusiness;
import Entity.CountNum;
import struts.form.FollowForm;


/**
 * MyEclipse Struts Creation date: 11-04-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/follow" name="followForm" scope="request"
 *                validate="true"
 * @struts.action-forward name="success" path="/Homepage.jsp"
 */
public class FollowAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FollowForm followForm = (FollowForm) form;// TODO Auto-generated method
		MicroblogBusiness mb = new MicroblogBusiness();
		if (mb.follow(followForm) && mb.befollowed(followForm)
				&& mb.updateAddFollowNum(followForm.getID())
				&& mb.updateAddFanNum(followForm.getFollow_id())
				&& mb.changeFollowstatus(followForm)) {
			CountNum cn = mb.getNum(followForm.getID());
			HttpSession session = request.getSession(true);
			session.setAttribute("num", cn);
			return mapping.findForward("success");
		}
		return null;

	}
}