/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.Globals;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-19-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="Success" path="/Regist.jsp"
 */
public class JapaneseAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Locale lc=new Locale("ja","jp");
		HttpSession session=request.getSession(true);
		request.setAttribute("flag", "1");
		session.setAttribute(Globals.LOCALE_KEY, lc);
		return mapping.findForward("success");
	}
}