/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import Business.MemberBusyness;
import Business.BaseBusyness;
import Business.UploadBean;

import struts.form.MemberAddForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2013
 * 
 * XDoclet definition:
 * @struts.action path="/memberAdd" name="memberAddForm" scope="request"
 * @struts.action-forward name="Fail" path="/MemberAdd.jsp"
 * @struts.action-forward name="Success" path="/HomePage.jsp"
 */
public class MemberAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MemberAddForm memberAddForm = (MemberAddForm) form;
		MemberBusyness mb=new MemberBusyness();
		UploadBean ub=new UploadBean();
		
		String path=request.getRealPath("/");
		
		FormFile file=memberAddForm.getFile();
		
		String fileName=file.getFileName();
		//上传后的文件名
		String fileinname=memberAddForm.getID()+fileName.substring(fileName.lastIndexOf("."));
		//上传后的路径 
		path=path+"files/"+fileinname;
		if(ub.upload(path, file)){
		if(mb.memberInfo(memberAddForm,fileinname)){
	
			return mapping.findForward("Success");
		}else{
			return mapping.findForward("Fail");
		}
		}
		return mapping.findForward("Success");
	}
}
