/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;
import Entity.Userinfo;
import Business.MemberBusyness;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2013
 * 
 * XDoclet definition:
 
 
 */
public class MemberDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		MemberBusyness mb=new MemberBusyness();
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
		Userinfo ui=mb.getMemberDetail(u.getID());
		request.setAttribute("detailmember",ui);
		return mapping.findForward("success");
	
	}
	}
