/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import struts.form.LoginForm;
import struts.form.MemberAddForm;
import struts.form.NewArticleForm;

import Business.BaseBusyness;
import Business.MemberBusyness;
import Business.MicroblogBusiness;
import Business.UploadBean;
import Entity.CountNum;

/** 
 * MyEclipse Struts
 * Creation date: 10-14-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="fail" path="/Homepage.jsp"
 * @struts.action-forward name="success" path="queryArticles.do"
 */
public class NewArticleAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		NewArticleForm newArticleForm = (NewArticleForm) form;// TODO Auto-generated method stub
		MicroblogBusiness mb=new MicroblogBusiness();
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
        UploadBean ub=new UploadBean();
		String path=request.getRealPath("/");
		FormFile file=newArticleForm.getFile();
		String fileName=file.getFileName();
		//上传后的文件名
		String fileinname=BaseBusyness.getStringID()+fileName.substring(fileName.lastIndexOf("."));
		//上传后的路径 
		path=path+"files/"+fileinname;
		if(ub.upload(path, file)){
		if(mb.newArticle(newArticleForm,u.getID(),fileinname)&&mb.updateAddArticleNum(u.getID())){
			CountNum cn=mb.getNum(u.getID());
			session.setAttribute("num",cn);
			return mapping.findForward("success");
			
		}else{
			return mapping.findForward("fail");
		}
		}
		return mapping.findForward("success");
	}
	}
