/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;
import Business.MicroblogBusiness;
import Entity.Comments;

/** 
 * MyEclipse Struts
 * Creation date: 11-15-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/QueryMyComments.jsp"
 */
public class QueryMyCommentsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		MicroblogBusiness mb=new MicroblogBusiness();
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
		ArrayList<Comments> ac=mb.queryMyComments(u.getID());
		request.setAttribute("commentsList", ac);
		return mapping.findForward("success");
	}
}