/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.AdminBusyness;
import Entity.Comments;
import Entity.Userinfo;

/** 
 * MyEclipse Struts
 * Creation date: 11-22-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="query" path="/QueryAllComments.jsp"
 * @struts.action-forward name="delete" path="/AdminDeleteComments.jsp"
 */
public class QueryAllCommentsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		AdminBusyness ab=new AdminBusyness();
		ArrayList<Comments> ac=ab.getAllComments();
		request.setAttribute("commentslist", ac);
		String flag=request.getParameter("flag");
		if("delComment".equals(flag)){
			return mapping.findForward("delete");
		}else{
			return mapping.findForward("query");
		}
	}
}