/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import Business.MemberBusyness;

import struts.form.RegistForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-12-2013
 * 
 * XDoclet definition:
 * @struts.action path="/regist" name="registForm" scope="request"
 * @struts.action-forward name="Fail" path="/Regist.jsp"
 * @struts.action-forward name="Success" path="/Login.jsp"
 */
public class RegistAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("text/html;charset=UTF-8");
		RegistForm registForm = (RegistForm) form;//填充form；从页面获取信息并保存
		MemberBusyness mb=new MemberBusyness();
		if("0".equals(registForm.getFlag())){//验证用户是否存在
			if(mb.isIDnull(registForm)){
				try {
					response.getWriter().print("用户名可以使用");
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}else{
				try {
					response.getWriter().print("用户名已存在");
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
			}
				}
				return null;
		}else{//注册
			if(mb.registMember(registForm)){
				request.setAttribute("ID",registForm.getID());
				return mapping.findForward("Success");//对应回送ActionForward
			}else{
				
				return mapping.findForward("Fail");
			}
		}

	}
}