/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;
import struts.form.SearchForm;

import Business.MicroblogBusiness;
import Entity.Userinfo;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2013
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/SearchResults.jsp"
 */
public class SearchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session=request.getSession(true);
		LoginForm u=(LoginForm)session.getAttribute("user");
		session.setAttribute("user", u);
		SearchForm searchForm=(SearchForm)form;
		MicroblogBusiness mb=new MicroblogBusiness();
		String s=searchForm.getSearch();
		ArrayList<Userinfo> aui=mb.getUsers(s,u.getID());
		request.setAttribute("userList", aui);
		return mapping.findForward("success");
			
		
	}
}