/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Business.AdminBusyness;
import Entity.Noticeboard;
import struts.form.UpdateNoticeboardForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-03-2013
 * 
 * XDoclet definition:
 * @struts.action path="/updateNoticeboard" name="updateNoticeboardForm" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/UpdateNoticeboard.jsp"
 * @struts.action-forward name="success" path="queryNoticeboard.do"
 */
public class UpdateNoticeboardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateNoticeboardForm updateNoticeboardForm = (UpdateNoticeboardForm) form;// TODO Auto-generated method stub
		AdminBusyness ab=new AdminBusyness();
		request.setAttribute("notice",updateNoticeboardForm);
		if(ab.updateNoticeboard(updateNoticeboardForm)){
			return mapping.findForward("success");
		}else{
			return mapping.findForward("fail");
		}
	}
}