/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import Business.BaseBusyness;
import Business.MemberBusyness;
import Business.UploadBean;
import Entity.Userinfo;
import struts.form.LoginForm;
import struts.form.UpdateMemberDetailForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-18-2013
 * 
 * XDoclet definition:
 * @struts.action path="/updateMemberDetail" name="updateMemberDetailForm" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/MemberDetail.jsp"
 * @struts.action-forward name="success" path="/queryMemberDetail"
 */
public class UpdateMemberDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateMemberDetailForm updateMemberDetailForm = (UpdateMemberDetailForm) form;// TODO Auto-generated method stub
		MemberBusyness mb=new MemberBusyness();
        UploadBean ub=new UploadBean();
		String path=request.getRealPath("/");
		FormFile file=updateMemberDetailForm.getFile();
		String fileName=file.getFileName();
		//上传后的文件名
		String fileinname=updateMemberDetailForm.getID()+fileName.substring(fileName.lastIndexOf("."));
		//上传后的路径 
		path=path+"files/"+fileinname;
		if(ub.upload(path, file)){
		if(mb.updateMemberDetail(updateMemberDetailForm,fileinname)){
			return mapping.findForward("success");
		}else{
			return mapping.findForward("fail");
		}
		}
		
		return mapping.findForward("success");
	}
	}
