/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-18-2013
 * 
 * XDoclet definition:
 * @struts.form name="addForwardDetailForm"
 */
public class AddForwardDetailForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private String forward_id;
	private String forward_content;
	private String article_id;
	private String ID;
	public String getForward_id() {
		return forward_id;
	}
	public void setForward_id(String forwardId) {
		forward_id = forwardId;
	}
	public String getForward_content() {
		return forward_content;
	}
	public void setForward_content(String forwardContent) {
		forward_content = forwardContent;
	}
	public String getArticle_id() {
		return article_id;
	}
	public void setArticle_id(String articleId) {
		article_id = articleId;
	}
	public String getID() {
		return ID;
	}
	public void setID(String iD) {
		ID = iD;
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}