/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-12-2013
 * 
 * XDoclet definition:
 * @struts.form name="commentsAddForm"
 */
public class CommentsAddForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String comments_id;
	private String comments_content;
	private String ID;
	private String article_id;
	public String getArticle_id() {
		return article_id;
	}
	public void setArticle_id(String articleId) {
		article_id = articleId;
	}
	public String getComments_id() {
		return comments_id;
	}
	public void setComments_id(String commentsId) {
		comments_id = commentsId;
	}
	public String getComments_content() {
		return comments_content;
	}
	public void setComments_content(String commentsContent) {
		comments_content = commentsContent;
	}
	public String getID() {
		return ID;
	}
	public void setID(String iD) {
		ID = iD;
	}
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}