/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-04-2013
 * 
 * XDoclet definition:
 * @struts.form name="followFormForm"
 */
public class FollowForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** fan_id property */
	private String fan_id;

	/** follow_id property */
	private String follow_id;
	private String ID;
	/*
	 * Generated Methods
	 */
	private String status;
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the fan_id.
	 * @return String
	 */
	public String getFan_id() {
		return fan_id;
	}

	/** 
	 * Set the fan_id.
	 * @param fan_id The fan_id to set
	 */
	public void setFan_id(String fan_id) {
		this.fan_id = fan_id;
	}

	/** 
	 * Returns the follow_id.
	 * @return String
	 */
	public String getFollow_id() {
		return follow_id;
	}

	/** 
	 * Set the follow_id.
	 * @param follow_id The follow_id to set
	 */
	public void setFollow_id(String follow_id) {
		this.follow_id = follow_id;
	}
}