/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 06-12-2013
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** PW property */
	private String PW;

	/** ID property */
	private String ID;

	/*
	 * Generated Methods
	 */
	private String checkcode;
	
	public String getCheckcode() {
		return checkcode;
	}

	public void setCheckcode(String checkcode) {
		this.checkcode = checkcode;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		//错误处理
		ActionErrors errors=new ActionErrors();
		if(PW!=null&&PW.length()<6){
			ActionMessage error=new ActionMessage("notnull","6");//notnull是资源属性文件里的name
			errors.add("notnullerror",error);
		}
		
		HttpSession session=request.getSession();
		String rand=(String)session.getAttribute("rand"); 
		if(checkcode==""){
			ActionMessage error=new ActionMessage("checkcodeNotnull");
			errors.add("checkcodeNotnull",error);
			}
		if(checkcode!=null&&checkcode.length()>0){
			if(!checkcode.equals(rand)){
				ActionMessage error=new ActionMessage("checkcodeerror");
				errors.add("checkcodeerror",error);
			}
			
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the PW.
	 * @return String
	 */
	public String getPW() {
		return PW;
	}

	/** 
	 * Set the PW.
	 * @param PW The PW to set
	 */
	public void setPW(String PW) {
		this.PW = PW;
	}

	/** 
	 * Returns the ID.
	 * @return String
	 */
	public String getID() {
		return ID;
	}

	/** 
	 * Set the ID.
	 * @param ID The ID to set
	 */
	public void setID(String ID) {
		this.ID = ID;
	}
}