/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-14-2013
 * 
 * XDoclet definition:
 * @struts.form name="newArticleFormForm"
 */
public class NewArticleForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String  article_id;
	public String getArticle_id() {
		return article_id;
	}

	public void setArticle_id(String articleId) {
		article_id = articleId;
	}
	private String ID;
	public String getID() {
		return ID;
	}

	/** 
	 * Set the ID.
	 * @param ID The ID to set
	 */
	public void setID(String ID) {
		this.ID = ID;
	}
	private FormFile file;
	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}
	/** file property */
	

	/** article_content property */
	private String article_content;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the file.
	 * @return String
	 */
	

	/** 
	 * Returns the article_content.
	 * @return String
	 */
	public String getArticle_content() {
		return article_content;
	}

	/** 
	 * Set the article_content.
	 * @param article_content The article_content to set
	 */
	public void setArticle_content(String article_content) {
		this.article_content = article_content;
	}
}