/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 06-12-2013
 * 
 * XDoclet definition:
 * @struts.form name="registForm"
 */
public class RegistForm extends ActionForm {
	/*
	 * Generated fields
	 */


	private String article_num;
	private String follow_num;
	private String fan_num;
	
	public String getArticle_num() {
		return article_num;
	}

	public void setArticle_num(String articleNum) {
		article_num = articleNum;
	}

	public String getFollow_num() {
		return follow_num;
	}

	public void setFollow_num(String followNum) {
		follow_num = followNum;
	}

	public String getFan_num() {
		return fan_num;
	}

	public void setFan_num(String fanNum) {
		fan_num = fanNum;
	}

	/** PW property */
	private String PW;

	/** PW_CFM property */
	private String PW_CFM;

	/** ID property */
	private String ID;

	/** ID_CFM property */
	
	
	private String flag;
	/*
	 * Generated Methods
	 */

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
				return null;
		
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the PW.
	 * @return String
	 */
	public String getPW() {
		return PW;
	}

	/** 
	 * Set the PW.
	 * @param PW The PW to set
	 */
	public void setPW(String PW) {
		this.PW = PW;
	}

	/** 
	 * Returns the PW_CFM.
	 * @return String
	 */
	public String getPW_CFM() {
		return PW_CFM;
	}

	/** 
	 * Set the PW_CFM.
	 * @param PW_CFM The PW_CFM to set
	 */
	public void setPW_CFM(String PW_CFM) {
		this.PW_CFM = PW_CFM;
	}

	/** 
	 * Returns the ID.
	 * @return String
	 */
	public String getID() {
		return ID;
	}

	/** 
	 * Set the ID.
	 * @param ID The ID to set
	 */
	public void setID(String ID) {
		this.ID = ID;
	}

	/** 
	 * Returns the ID_CFM.
	 * @return String
	 */
	
}