/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-03-2013
 * 
 * XDoclet definition:
 * @struts.form name="updateNoticeboardForm"
 */
public class UpdateNoticeboardForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** noticeboard property */
	private String notice_content;
	private String notice_id;
	public String getNotice_content() {
		return notice_content;
	}
	public void setNotice_content(String noticeContent) {
		notice_content = noticeContent;
	}
	public String getNotice_id() {
		return notice_id;
	}
	public void setNotice_id(String noticeId) {
		notice_id = noticeId;
	}
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
}